### PR TITLE
Unpack hash type

### PR DESCRIPTION
**Pull request by usedbytes**

### CODE REVIEW

**Comment by usedbytes** [comment]
Let me know what you think of this - as you suggested I'm just checking the length

**Comment by osm0sis** [comment]
Hi! Thanks again.

I'm a little curious about the math to reduce it to a switch function. Wouldn't it be easier to just increase the size of the id in the header file so that it'll read enough for sha256 then parse it out to a valid sha1 with an if-else (if the last half is all 00/null)?

**Comment by usedbytes** [comment]
Not sure exactly what you mean by reading enough for a sha256 - we always read the whole header which includes 32 bytes for the ID field. A sha1 is only 20 bytes long, so the size of the header doesn't change for sha256, it's just that all 32 bytes of the ID field are used instead of only the first 20.

Perhaps building the mask thing is a bit convoluted, I just was trying to avoid `if`s with 8 clauses. Any preference out of the two alternatives below?

Either just check each word explicitly:
```
	uint32_t *id = hdr->id;
	if (id[0] != 0 && id[1] != 0 && id[2] != 0 && id[3] != 0 &&
	    id[4] != 0 && id[5] != 0 && id[6] != 0 && id[7] != 0) {
		return "sha256";
	} else if (id[0] != 0 && id[1] != 0 && id[2] != 0 && id[3] != 0 &&
		   id[4] != 0 && id[5] == 0 && id[6] == 0 && id[7] == 0) {
		return "sha1";
	} else {
		return "unknown";
	}
```

Or loop to find the first zero:
```
	const int n_elems = sizeof(hdr->id) / sizeof(hdr->id[0]);
	int i;

	for (i = 0; i < n_elems; i++) {
		if (!hdr->id[i])
			break;
	}

	if (i == n_elems)
		return "sha256";
	else if (i == 5 && (hdr->id[5] == hdr->id[6] == hdr->id[7] == 0))
		return "sha1";
	else
		return "unknown";
```

Cheers!

**Comment by usedbytes** [comment]
p.s. I did think about just looking for the first byte that is zero in the hash to determine its length, like `strnlen((char *)hdr->id, sizeof(hdr->id));` or something, but the chances of an individual byte in the hash being zero is relatively high, so it might break easily. By checking 32 bits at a time against zero the odds of making a mistake look a lot lower.

**Comment by osm0sis** [comment]
Sorry! I totally read the header wrong earlier; didn't realize it was already a 32 byte field.

I agree the first zero would be often too early. My original thought would be that to parse the hdr->id you could split it into 2 words: 20 characters and the remaining 12 characters.

Then only test the second word. If the second word is completely null then assume "sha1", if not null then assume "sha256". Maybe a sanity check to make sure the first word isn't also null somehow ("unknown"). This looks closer to your first example, I think.

Let me know if what you think's best and we'll go with it, provided it's all compiled, tested and working for both sha1 and sha256 test files. 🙂👍

**Comment by usedbytes** [comment]
Updated the branch using the first example.

Quick test:
```
$ git log --oneline -1
b8dc5ba3 unpackbootimg: Add support for writing out hash type

$ make clean
rm -f mkbootimg mkbootimg-static mkbootimg.o unpackbootimg
unpackbootimg-static unpackbootimg.o mkbootimg.exe mkbootimg-static.exe
unpackbootimg.exe unpackbootimg-static.exe
rm -f libmincrypt.a Makefile.~
make -C libmincrypt clean
make[1]: Entering directory '/tmp/mkbootimg/libmincrypt'
rm -f dsa_sig.o p256.o p256_ec.o p256_ecdsa.o rsa.o sha.o sha256.o
libmincrypt.a
make[1]: Leaving directory '/tmp/mkbootimg/libmincrypt'

$ make
make -C libmincrypt
make[1]: Entering directory '/tmp/mkbootimg/libmincrypt'
gcc -o dsa_sig.o -ffunction-sections -O3 -c dsa_sig.c -I..
gcc -o p256.o -ffunction-sections -O3 -c p256.c -I..
gcc -o p256_ec.o -ffunction-sections -O3 -c p256_ec.c -I..
gcc -o p256_ecdsa.o -ffunction-sections -O3 -c p256_ecdsa.c -I..
gcc -o rsa.o -ffunction-sections -O3 -c rsa.c -I..
gcc -o sha.o -ffunction-sections -O3 -c sha.c -I..
gcc -o sha256.o -ffunction-sections -O3 -c sha256.c -I..
ar rc libmincrypt.a dsa_sig.o p256.o p256_ec.o p256_ecdsa.o rsa.o sha.o
sha256.o
cp libmincrypt.a ..
make[1]: Leaving directory '/tmp/mkbootimg/libmincrypt'
gcc -o mkbootimg.o -ffunction-sections -O3 -c mkbootimg.c -I. -Werror
gcc -o mkbootimg mkbootimg.o -L. -lmincrypt -Wl,--gc-sections -s
gcc -o unpackbootimg.o -ffunction-sections -O3 -c unpackbootimg.c -Werror
gcc -o unpackbootimg unpackbootimg.o -Wl,--gc-sections -s

$ ./mkbootimg --kernel zImage --id -o boot.sha1.img
0xac648aec47053cdc50a635f61676adce121010d2000000000000000000000000

$ ./unpackbootimg -i boot.sha1.img -o . >/dev/null

$ cat boot.sha1.img-hash
sha1

$ ./mkbootimg --kernel zImage --hash sha256 --id -o boot.sha256.img
0x925b3abacc54f4f496407087cfe55f102ae7e1a47deea4e956947e3ef4e34aec

$ ./unpackbootimg -i boot.sha256.img -o . >/dev/null

$ cat boot.sha256.img-hash
sha256
```

**Comment by osm0sis** [comment]
Thanks again! Looks good. :smiley:

**Pull request merged**
