### PR TITLE
fix mac compile errors

### PR DESCRIPTION
**Pull request by erfanoabdi**
i've only tested this on mac, not sure "-dead_strip" is working on linux too

### CODE REVIEW

**Comment by osm0sis** [comment]
If you can rewrite this as an if-statement that detects and does this on macOS-only then I'll accept it. The custom optimizations work fine on every other platform so I won't remove them completely just for the odd-man-out of the *nix world. 😉 

The last similar pull request (https://github.com/osm0sis/mkbootimg/pull/1) didn't need to turn off -Werror, just drop --gc-sections, any particular reason you did this?

**Comment by erfanoabdi** [comment]
thanks, i added if-statement as you said and i re added Werrors but 
with Werror this can't compile correctly look at warnings about uint8_t and char* converting : 
```
unpackbootimg.c:140:31: warning: passing 'uint8_t [512]' to parameter of type
      'char *' converts between pointers to integer types with different sign
      [-Wpointer-sign]
    write_string_to_file(tmp, header.cmdline);
                              ^~~~~~~~~~~~~~
unpackbootimg.c:33:45: note: passing argument to parameter 'string' here
void write_string_to_file(char* file, char* string)
                                            ^
unpackbootimg.c:145:31: warning: passing 'uint8_t [16]' to parameter of type
      'char *' converts between pointers to integer types with different sign
      [-Wpointer-sign]
    write_string_to_file(tmp, header.name);
                              ^~~~~~~~~~~
unpackbootimg.c:33:45: note: passing argument to parameter 'string' here
void write_string_to_file(char* file, char* string)
                                            ^
2 warnings generated.
```

i think fixing this warnings is better than disabling Werror

**Comment by osm0sis** [comment]
Interesting. There are no warnings on all the other platforms I cross-compile to/from, so it compiles fine with -Werror. It's unclear if fixing it for macOS/Darwin would break it elsewhere..

We can split the difference and you can add -Werror to CFLAGS only on non-Darwin, if you want to include another commit to add that, it amend it into your last one. What version of GCC are you using and are you able to use a newer one to test?

**Comment by erfanoabdi** [comment]
OK thanks my gcc version is 4.2.1 but it's latest version of xCode on macOS 10.12 : 
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
anyway, you're right
i'll add new commit to remove Werror only for macOS

**Comment by osm0sis** [comment]
Hmm that's a pretty low version. All the compilers I'm using are gcc 4.9.x and I've added fixes for 5.0+ already. Any way you can update your gcc and try again to see if the last commit is necessary?

**Comment by erfanoabdi** [comment]
Yeah unfortunately it's really old version for newest version of xCode, actually for updating gcc of Mac, people have to build gcc from source or install it from homebrew (gnu Linux repo on Mac), at all I think my last commit isn't necessary for new gcc. 
Let me check maybe we can fix c file with casting or change Darwin if to gcc version

**Comment by erfanoabdi** [comment]
now you can choose between makefile bypassing or casting on c file :) 
check new pull : https://github.com/osm0sis/mkbootimg/pull/5

**Comment by osm0sis** [comment]
Your casts in the other request cross-compile on all my host/target platforms with no issue and that seems like the cleaner method overall, so I'll go with that one! Thanks! 😃

**Pull request closed without merging**
