### PR TITLE
unpackbootimg: Fixup compilation errors

### PR DESCRIPTION
**Pull request by corphish**

### CODE REVIEW

**Comment by osm0sis** [comment]
Compiling how? I have no such errors using the included makefile. Also, I commented out that part about the magic on purpose. :+1:

**Comment by corphish** [comment]
Well! I faced errors and fixed them.
About the magic thing, was interested to know what would be the result. So I uncommented to check that. While commiting, I was unaware of this change

**Comment by osm0sis** [comment]
Oh I hear you. Sounds good, but I'd like to know how you're compiling, with what gcc, on what host, for what target, etc. that you got errors.

**Comment by osm0sis** [comment]
Merged the other version of this fix instead. Thanks!

**Pull request closed without merging**
